site_name: Accessing Monitor Service Data in Citrix Cloud
site_description: Accessing Monitor Service Data in Citrix Cloud
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - footnotes
  - meta

pages:
- Home: index.md
